//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_career
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_career()
        {
            this.t_use_lang = new HashSet<t_use_lang>();
        }
    
        public int career_no { get; set; }
        public string emp_cd { get; set; }
        public string item_nm { get; set; }
        public string item_detail { get; set; }
        public Nullable<sbyte> work_class_sp { get; set; }
        public Nullable<sbyte> work_class_ra { get; set; }
        public Nullable<sbyte> work_class_bd { get; set; }
        public Nullable<sbyte> work_class_sd { get; set; }
        public Nullable<sbyte> work_class_dd { get; set; }
        public Nullable<sbyte> work_class_pg { get; set; }
        public Nullable<sbyte> work_class_pt { get; set; }
        public Nullable<sbyte> work_class_st { get; set; }
        public Nullable<sbyte> work_class_etc { get; set; }
        public string position_cd { get; set; }
        public string os_nm { get; set; }
        public string tools_nm { get; set; }
        public Nullable<System.DateTime> work_start_date { get; set; }
        public Nullable<System.DateTime> work_end_date { get; set; }
        public string customer_cd { get; set; }
        public string work_site_nm { get; set; }
        public string remarks { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<sbyte> deleted { get; set; }
    
        public virtual m_customer m_customer { get; set; }
        public virtual m_employee m_employee { get; set; }
        public virtual m_position m_position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_use_lang> t_use_lang { get; set; }
        CareerTerm careerterm = new CareerTerm();

        public class CareerTerm
        {
            public string Maneger { get; set; }
            public string Leader { get; set; }
            public string Submane { get; set; }
            public string Member { get; set; }
        }
    }
}
